name: "Test"
on:
  push:
    branches:
      - master

jobs:
  end-standard-change-deploy-failed:
    name: End Standard Change - Deploy Failed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Start Standard Change
        uses: byu-oit/github-action-start-standard-change@v1
        id: start-standard-change
        with:
          client-key: ${{ secrets.CLIENT_KEY }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          template-id: ${{ secrets.TEST_TEMPLATE_ID }}
      - name: End Standard Change
        uses: ./
        with:
          client-key: ${{ secrets.CLIENT_KEY }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          change-sys-id: ${{ steps.start-standard-change.outputs.change-sys-id }}
          work-start: ${{ steps.start-standard-change.outputs.work-start }}
          success: 'false'

  end-standard-change-deploy-successful:
    name: End Standard Change - Deploy Successful
    needs: end-standard-change-deploy-failed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Start Standard Change
        uses: byu-oit/github-action-start-standard-change@v1
        id: start-standard-change
        with:
          client-key: ${{ secrets.CLIENT_KEY }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          template-id: ${{ secrets.TEST_TEMPLATE_ID }}
      - name: End Standard Change
        uses: ./
        with:
          client-key: ${{ secrets.CLIENT_KEY }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          change-sys-id: ${{ steps.start-standard-change.outputs.change-sys-id }}
          work-start: ${{ steps.start-standard-change.outputs.work-start }}
          success: 'true'
