name: "Test"
on:
  push:
    branches:
      - master

jobs:
  end-standard-change-deploy-failed:
    name: End Standard Change - Deploy Failed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: End Standard Change
        uses: ./
        with:
          client-key: ${{ secrets.CLIENT_KEY }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          change-sys-id: ${{ secrets.TEST_CHANGE_SYS_ID }}
          success: 'false'

  end-standard-change-deploy-successful:
    name: End Standard Change - Deploy Successful
    needs: end-standard-change-deploy-failed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: End Standard Change
        uses: ./
        with:
          client-key: ${{ secrets.CLIENT_KEY }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          change-sys-id: ${{ secrets.TEST_CHANGE_SYS_ID }}
          success: 'true'
